config/routes.rb
Rouvignac::Application.routes.draw do
  scope "(:locale)", :locale => /en|fr|es|de|nl/, defaults: { locale: 'fr' } do
    get "home/index"
    root :to => 'home#index'
    get "hameau-en-vente", to: "home#sale"
    resources :gites, only: [:index, :show]
    match 'gites/:id/update2' => 'gites#update2', via: [:put, :patch]
    get "administration/index"
    resources :photos, only: [:index]
    resources :tarifs, only: [:show]
    get 'tarifs', to: 'tarifs#show', defaults: { id: 1 }
    resources :events do
      collection do
        patch "update_event"
        delete "delete_event"
      end
    end
    namespace :crm do
      resources :gites do
        member do
          get :edit_calendar
        end
      end
      resources :calendar, only: [:index]
      resources :photos
      resources :energy_prices
      resources :clients
      resources :reservations
      resources :tarifs, except: [:new, :create, :index, :destroy]
      resources :lease_agreements, only: [:index, :show]
    end
    #match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get]
    get 'contact' => 'contact#new'#, :as => 'contact'#, :via => :get
    #post 'contact' => 'contact#create'#, :as => 'contact'#, :via => :post
    devise_for :admins
    get "administration" => "administration#index"
    get 'calendar' => 'calendar#index'
    get 'all_events' => 'calendar#all_events'
  end
end

app/models/gite.rb
class Gite < ApplicationRecord

  serialize :beds, Array
  #attr_accessible :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :title, :image
  default_scope { where.not(title: "Prochainement") }
  #def to_param
  #  "#{id} #{title}".parameterize
  #end

  def available_bed_furnitures
    all_bed_types = %w(bed_120x190 bed_160x200 bed_140x190 bed_90x190 bed_90x200 armchair_90x190)
    present_furnitures = []
    all_bed_types.each{|l| present_furnitures << l unless self.send(l) == 0 }
    present_furnitures
  end

  def get_beds
    self.available_bed_furnitures.map do |furniture|
      self.send(furniture).to_s + " " + I18n.t("crm.gites.#{furniture}")
    end
  end

  has_many :events
  has_many :reservations
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :text10, ImageUploader
  mount_uploader :text9, ImageUploader
  mount_uploader :text8, ImageUploader
  mount_uploader :text7, ImageUploader
  mount_uploader :text6, ImageUploader
  mount_uploader :text5, ImageUploader
  mount_uploader :text4, ImageUploader
  mount_uploader :image, ImageUploader

  def surface
    text2.split(" ").last.gsub("(", "").gsub(")","")
  end

end

app/controllers/crm/gites_controller.rb
class Crm::GitesController < Crm::BaseController

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update]
  def index
    @gites = Gite.order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gites }
    end
  end

  def show
    @gite = Gite.friendly.find(current_gite)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gite }
    end
  end

  def new
    @gite = Gite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gite }
    end
  end

  def edit
    @gite = Gite.find(current_gite)
  end

  def edit_calendar
    @gite = Gite.find_by(slug: current_gite)
  end

  def create
    @gite = Gite.new(gite_params)

    respond_to do |format|
      if @gite.save
        format.html { redirect_to @gite, notice: 'Gite was successfully created.' }
        format.json { render json: @gite, status: :created, location: @gite }
      else
        format.html { render action: "new" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gite = Gite.find(current_gite)
    respond_to do |format|
      if @gite.update_attributes(gite_params)
        format.html { redirect_to [:crm, @gite], notice: 'Gite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gite = Gite.find(current_gite)
    @gite.destroy

    respond_to do |format|
      format.html { redirect_to gites_url }
      format.json { head :no_content }
    end
  end

  private
  def current_gite
    params.require(:id)
  end
  def gite_params
    params.require(:gite).permit(:id, :title, :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :created_at, :updated_at, :slug, :image, :bed_120x190, :bed_160x200, :bed_140x190, :bed_90x190, :bed_90x200, :armchair_90x190, :energy_type, :cleaning_price, beds: [])
  end
end

app/controllers/gites_controller.rb
class GitesController < ApplicationController
  # GET /gites
  # GET /gites.json
  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update]
  def index
    #binding.pry
    @gites = Gite.order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gites }
    end
  end

  # GET /gites/1
  # GET /gites/1.json
  def show
    @gite = Gite.friendly.find(current_gite)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gite }
    end
  end

  # GET /gites/new
  # GET /gites/new.json
  def new
    @gite = Gite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gite }
    end
  end

  # GET /gites/1/edit
  def edit
    @gite = Gite.find(current_gite)
  end

  # POST /gites
  # POST /gites.json
  def create
    @gite = Gite.new(gite_params)

    respond_to do |format|
      if @gite.save
        format.html { redirect_to @gite, notice: 'Gite was successfully created.' }
        format.json { render json: @gite, status: :created, location: @gite }
      else
        format.html { render action: "new" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gites/1
  # PUT /gites/1.json
  def extract_params(params)
      attr = {}
      params[:content].each { |key, value| attr[key.to_sym] = value['value'] }
      attr
  end
  def update
    @gite = Gite.find(current_gite)

    respond_to do |format|
      if @gite.update_attributes(extract_params(params))
        format.html { redirect_to @gite, notice: 'Gite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update2
    @gite = Gite.find(current_gite)
    #binding.pry
    respond_to do |format|
      if @gite.update_attributes(gite_params)
        format.html { redirect_to @gite, notice: 'Gite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gites/1
  # DELETE /gites/1.json
  def destroy
    @gite = Gite.find(current_gite)
    @gite.destroy

    respond_to do |format|
      format.html { redirect_to gites_url }
      format.json { head :no_content }
    end
  end

  private
  def current_gite
    params.require(:id)
  end
  def gite_params
    params.require(:gite).permit(:id, :title, :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :created_at, :updated_at, :slug, :image)
  end
end

app/helpers/gites_helper.rb
module GitesHelper
end

app/views/gites/_formUpdate2.html.erb
<%= form_for @gite, :url => { :id => @gite.id, :action => "update2" }, :html => { :method => :put, :multipart => true } do |f| %>
  <% if @gite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gite.errors.count, "error") %> prohibited this gite from being saved:</h2>

      <ul>
      <% @gite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <h1>Modifier les Images du Gîte ainsi que ses spécifications</h1>


  <br/>
  <!--<div class="field">
    <%= f.label :text3 %>Description du Gîte<br />
    <%= f.text_area :text3 %>
  </div>-->
  <div class="field">
    <%#= f.label :text10 %><span style="font-weight:bold;color:red;">Photo Principale (doit avoir une taille de 520x400px)<br />
    <%= image_tag @gite.text10_url, :size => "50x50" if @gite.text10_url %>
    <%= f.file_field :text10 %>
  </div>
  <div class="field">
    <%#= f.label :text9 %>Photo 2<br />
    <%= image_tag @gite.text9_url, :size => "50x50" if @gite.text9_url %>
    <%= f.file_field :text9 %>
  </div>
  <div class="field">
    <%#= f.label :text8 %>Photo 3<br />
    <%= image_tag @gite.text8_url, :size => "50x50" if @gite.text8_url %>
    <%= f.file_field :text8 %>
  </div>
  <div class="field">
    <%#= f.label :text7 %>Photo 4<br />
    <%= image_tag @gite.text7_url, :size => "50x50" if @gite.text7_url %>
    <%= f.file_field :text7 %>
  </div>
  <div class="field">
    <%#= f.label :text6 %>Photo 5<br />
    <%= image_tag @gite.text6_url, :size => "50x50" if @gite.text6_url %>
    <%= f.file_field :text6 %>
  </div>
  <div class="field">
    <%#= f.label :text5 %>Photo 6<br />
    <%= image_tag @gite.text5_url, :size => "50x50" if @gite.text5_url %>
    <%= f.file_field :text5 %>
  </div>
  <div class="field">
    <%#= f.label :text4 %>Photo 7<br />
    <%= image_tag @gite.text4_url, :size => "50x50" if @gite.text4_url %>
    <%= f.file_field :text4 %>
  </div>
  <div class="field">
    <%#= f.label :image %>Photo 8<br />
    <%= image_tag @gite.image_url, :size => "50x50" if @gite.image_url %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%#= f.label :text1 %> Type de Gîte :<br />
    <%#= binding.pry %>
    <%= f.select :text1, options_for_select([ ["studio", "studio-sort"], ["studio-mezzanine", "studio-mezzanine-sort"], ["F2", "f2-sort"], ["F3", "f3-sort"], ["F4", "f4-sort"], ["F5", "f5-sort"] ], @gite.text1) %>
  </div>
  <div class="field">
    <%#= f.label :text2 %>Nombre de personnes :<br />
    <%= f.text_field :text2 %>
  </div>
  <div class="actions">
    <%= f.submit :style => "background:green;" %>
  </div>
<% end %>

app/views/gites/index.html.erb
<style>
tr td{
    border-bottom: 1px solid black;
    padding-top: 10px;
    padding-bottom: 10px;
}
tr th{
    border-bottom: 1px solid black;
    padding-top: 10px;
    padding-bottom: 10px;
}
</style>


<!-- **Container** -->
    <div class="container-fluid">

        <!-- **Primary Section** -->
        <section id="primary" class="content-full-width">


            <div class="sorting-container">
                <a href="#" title="" class="active-sort" data-filter=".all-sort"> <%= t 'gites.menu.tous' %> </a>
                <a href="#" title="" data-filter=".studio-sort"> <%= t 'gites.menu.studio' %> </a>
                <a href="#" title="" data-filter=".studio-mezzanine-sort"> <%= t 'gites.menu.studiom' %> </a>
                <a href="#" title="" data-filter=".f2-sort"> <%= t 'gites.menu.f2' %> </a>
                <a href="#" title="" data-filter=".f3-sort"> <%= t 'gites.menu.f3' %> </a>
                <a href="#" title="" data-filter=".f4-sort"> <%= t 'gites.menu.f4' %> </a>
                <a href="#" title="" data-filter=".f5-sort"> <%= t 'gites.menu.f5' %> </a>
            </div>

            <!--<style media="screen">
              .portfolio{
                border-bottom: none !important;
              }
            </style>-->


            <div class="portfolio-container gallery">

                <% @gites.each do |gite| %>

                    <div class="portfolio four-column all-sort <%= gite.text1 %>" >

                        <div class="portfolio-thumb">
                            <%= link_to gite_url(gite, locale: I18n.locale), :class => 'lik' do %>
                                <%= image_tag gite.text10_url if gite.text10_url %>
                            <% end %>
                        </div>

                        <%= link_to gite_url(gite, locale: I18n.locale) do %>
                          <div class="portfolio-detail">
                              <h5> <%= gite.title %> </h5>
                              <p> <%= gite.text2 %> </p>
                          </div>
                        <% end %>

                    </div>

                <% end %>

            </div>


            <div class="clear"> </div>
            <div class="hr-invisible-small"> </div>


        </section><!-- **Primary Section** -->

    </div><!-- **Container - End** -->

            <div class="clear"> </div>
            <div class="hr-invisible-small"> </div>

app/views/gites/show.html.erb
<style media="screen">
  .img-responsive{display:block;max-width:100%;height:auto;border-radius:3px;}
  ul{list-style: none;}
  .border-title{margin: 0px 0px 25px;}
  p{text-align: justify;}
</style>

<%#= javascript_include_tag 'calendar' %>



      <!-- **Container** -->
      <div class="container-fluid">

        <% if admin_signed_in? %>

          <br/>

          <div class="row">

            <div class="col-md-12">
              <div id='calendar'></div>
            </div>

          </div> <!-- end row -->

        <% else %>

          <br/>
          <br/>

          <div class="row">

            <div class="col-md-6">
              <!--<h2> Gîte <%#= raw(@gite.title) %> </h2>
              <p class="price"> <%#= raw(@gite.text2) %> </p>
              <div class="description">
                <div id="text3"><p><%#= raw(@gite.text3) %></p></div>
              </div>-->

              <div class="border-title"> <h3> Gîte <%= raw(@gite.title) + " : " + raw(@gite.text2) %> <span> </span> </h3> </div>

                              <div class="tabs-container">
                                  <ul class="tabs-frame">
                                      <li><a href="#"> <%= t 'gites.gite.informations' %> </a></li>
                                      <li><a href="#"> <%= t 'gites.gite.prix' %> </a></li>
                                  </ul>
                                  <div class="tabs-frame-content">
                                      <p>
                                          <%= raw(@gite.text3) %>
                                      </p>
                                  </div>
                                  <div class="tabs-frame-content">
                                      <p>
                                          <%#= binding.pry %>
                                          <h5><%= t 'tarif.periode1' %></h5>
                                          <p><%= raw Tarif.first.send("prix#{@gite.slug.first}1") %></p>

                                          <h5><%= t 'tarif.periode2' %></h5>
                                          <p><%= raw Tarif.first.send("prix#{@gite.slug.first}2") %></p>

                                          <h5><%= t 'tarif.periode3' %></h5>
                                          <p><%= raw Tarif.first.send("prix#{@gite.slug.first}3") %></p>

                                      </p>
                                  </div>
                              </div><!-- **Tabs Container - End** -->

            </div>

            <div class="col-md-6">
              <div id='public_calendar'></div>
            </div>

          </div> <!-- end row -->

        <% end %>

        <hr/>

        <ul class="row gallery">
              <% if @gite.text10_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text10.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text10.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
              <% if @gite.text9_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text9.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text9.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
              <% if @gite.text8_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text8.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text8.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
              <% if @gite.text7_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text7.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text7.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
        </ul>

        <ul class="row gallery">

              <% if @gite.text6_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text6.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text6.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
              <% if @gite.text5_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text5.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text5.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
              <% if @gite.text4_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.text4.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text4.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
              <% if @gite.image_url %>
                <li class="col-md-3">
                  <a href="<%= @gite.image.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.image.standard.url, class: "img-responsive" %> </a>
                </li>
              <% end %>
        </ul>

      </div><!-- **Container - End** -->