config/routes.rb
Rouvignac::Application.routes.draw do
  scope "(:locale)", :locale => /en|fr|es|de|nl/, defaults: { locale: 'fr' } do
    get "home/index"
    root :to => 'home#index'
    get "hameau-en-vente", to: "home#sale"
    resources :gites, only: [:index, :show]
    match 'gites/:id/update2' => 'gites#update2', via: [:put, :patch]
    get "administration/index"
    resources :photos, only: [:index]
    resources :tarifs, only: [:show]
    get 'tarifs', to: 'tarifs#show', defaults: { id: 1 }
    resources :events do
      collection do
        patch "update_event"
        delete "delete_event"
      end
    end
    namespace :crm do
      resources :gites do
        member do
          get :edit_calendar
        end
      end
      resources :calendar, only: [:index]
      resources :photos
      resources :energy_prices
      resources :clients
      resources :reservations
      resources :tarifs, except: [:new, :create, :index, :destroy]
      resources :lease_agreements, only: [:index, :show]
    end
    #match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get]
    get 'contact' => 'contact#new'#, :as => 'contact'#, :via => :get
    #post 'contact' => 'contact#create'#, :as => 'contact'#, :via => :post
    devise_for :admins
    get "administration" => "administration#index"
    get 'calendar' => 'calendar#index'
    get 'all_events' => 'calendar#all_events'
  end
end

app/models/gite.rb
class Gite < ApplicationRecord

  serialize :beds, Array
  #attr_accessible :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :title, :image
  default_scope { where.not(title: "Prochainement") }
  #def to_param
  #  "#{id} #{title}".parameterize
  #end

  def available_bed_furnitures
    all_bed_types = %w(bed_120x190 bed_160x200 bed_140x190 bed_90x190 bed_90x200 armchair_90x190)
    present_furnitures = []
    all_bed_types.each{|l| present_furnitures << l unless self.send(l) == 0 }
    present_furnitures
  end

  def get_beds
    self.available_bed_furnitures.map do |furniture|
      self.send(furniture).to_s + " " + I18n.t("crm.gites.#{furniture}")
    end
  end

  has_many :events
  has_many :reservations
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :text10, ImageUploader
  mount_uploader :text9, ImageUploader
  mount_uploader :text8, ImageUploader
  mount_uploader :text7, ImageUploader
  mount_uploader :text6, ImageUploader
  mount_uploader :text5, ImageUploader
  mount_uploader :text4, ImageUploader
  mount_uploader :image, ImageUploader

  def surface
    text2.split(" ").last.gsub("(", "").gsub(")","")
  end

end

app/controllers/crm/base_controller.rb
class Crm::BaseController < ActionController::Base
  protect_from_forgery

  layout 'crm/application'

end

app/controllers/crm/calendar_controller.rb
# encoding: UTF-8
class Crm::CalendarController < Crm::BaseController

  before_action :authenticate_admin!

  def index

  end

  def all_events
    all_events = []
    Gite.all.map do |gite|
      gite_events = gite.events.where("start_at >= :start OR end_at <= :end", start: params[:start], end: params[:end] )
      gite_events = gite_events.map{|event| {id: event.id, start: event.start_at, end: event.end_at, color: RED, title: gite.title}}
      gite_events = gite_events.sort_by{|hsh| hsh[:start]}
      previous_event_end = []
      gite_availabilities = []
      all_gite_events = []
      all_gite_events << gite_events
      # create availabilities for beginning and end of month
      unless gite_events.empty?
        if(gite_events.first[:start] - DateTime.parse(params[:start]) >= 86400)
          gite_availabilities << {start: DateTime.parse(params[:start]), end: gite_events.first[:start], color: GREEN, title: gite.title}
        end
        if((DateTime.parse(params[:end]).to_date - gite_events.last[:end].to_date).to_i >= 1)
          gite_availabilities << {start: gite_events.last[:end], end: DateTime.parse(params[:end]), color: GREEN, title: gite.title}
        end
      else
        gite_availabilities << {start: DateTime.parse(params[:start]), end: DateTime.parse(params[:end]), color: GREEN, title: gite.title}
      end
      # create availabilities between unavailabilities..
      gite_events.each_with_index do |event, i|
        previous_event_end << event[:end]
        unless i == 0
          if(event[:start] - previous_event_end[-2]) >= 86400
            gite_availabilities << {start: previous_event_end[-2], end: event[:start], color: GREEN, title: gite.title}
          end
        end
      end
      all_gite_events << gite_availabilities
      all_events << all_gite_events
    end
    #binding.pry
    render json: all_events.flatten
  end


end

app/controllers/crm/clients_controller.rb
class Crm::ClientsController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :current_client, only: [:edit, :show, :update, :destroy]

  def index
    clients = params[:reset].present? ? clients = Client.order(:last_name) : clients = Client.filter(filtering_params(params)).order(:last_name)
    # series = params[:reset].present? ? series = Serie.order(:id) : series = Serie.filter(filtering_params(params)).order(:id)
    # @clients = Client.filter(filtering_params(params)).order(:last_name)
    @clients = clients
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to [:crm, @client], notice: 'Client was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to [:crm, @client], notice: 'Client was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if @client.destroy
      redirect_to crm_clients_path, notice: 'Client was successfully destroyed.'
    else
      redirect_to :back
    end
  end

  private
  def current_client
    @client = Client.find params.require(:id)
  end

  def client_params
    params.require(:client).permit(:id, :first_name, :last_name, :email, :phone_number, :street_name, :street_number, :postal_code, :city, :number_of_person, :mobile_phone_number)
  end

  def filtering_params(params)
    params.slice(:search_by_last_name)
  end

end

app/controllers/crm/energy_prices_controller.rb
class Crm::EnergyPricesController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :energy_price, only: [:edit, :show, :update]

  def index
    @energy_prices = EnergyPrice.all
  end

  def create
    @energy_price = EnergyPrice.new(energy_price_params)
    if @energy_price.save
      redirect_to [:crm, @energy_price], notice: 'energy_price was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @energy_price = EnergyPrice.new
  end

  def edit
  end

  def update
    if @energy_price.update_attributes(energy_price_params)
      redirect_to [:crm, @energy_price], notice: 'energy_price was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def energy_price
    @energy_price = EnergyPrice.find params.require(:id)
  end

  def energy_price_params
    params.require(:energy_price).permit(:id, :energy_type, :price)
  end

end

app/controllers/crm/gites_controller.rb
class Crm::GitesController < Crm::BaseController

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update]
  def index
    @gites = Gite.order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gites }
    end
  end

  def show
    @gite = Gite.friendly.find(current_gite)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gite }
    end
  end

  def new
    @gite = Gite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gite }
    end
  end

  def edit
    @gite = Gite.find(current_gite)
  end

  def edit_calendar
    @gite = Gite.find_by(slug: current_gite)
  end

  def create
    @gite = Gite.new(gite_params)

    respond_to do |format|
      if @gite.save
        format.html { redirect_to @gite, notice: 'Gite was successfully created.' }
        format.json { render json: @gite, status: :created, location: @gite }
      else
        format.html { render action: "new" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gite = Gite.find(current_gite)
    respond_to do |format|
      if @gite.update_attributes(gite_params)
        format.html { redirect_to [:crm, @gite], notice: 'Gite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gite = Gite.find(current_gite)
    @gite.destroy

    respond_to do |format|
      format.html { redirect_to gites_url }
      format.json { head :no_content }
    end
  end

  private
  def current_gite
    params.require(:id)
  end
  def gite_params
    params.require(:gite).permit(:id, :title, :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :created_at, :updated_at, :slug, :image, :bed_120x190, :bed_160x200, :bed_140x190, :bed_90x190, :bed_90x200, :armchair_90x190, :energy_type, :cleaning_price, beds: [])
  end
end

app/controllers/crm/lease_agreements_controller.rb
class Crm::LeaseAgreementsController < Crm::BaseController

  before_action :authenticate_admin!

  def show
    #binding.pry
    @reservation = Reservation.find params.require(:id)
    @client = @reservation.client
    @gite = @reservation.gite
    respond_to do |format|
      format.pdf do
        render :pdf => "lease_agreement.pdf",
          :disposition => "inline",
          :template => "crm/lease_agreements/show.pdf.erb",
          :layout => "crm/pdf_layout.html.erb"#,
          #viewport_size: "1280x1024"
      end 
      #format.html
    end
      # format.html
      # format.pdf do
      #   render pdf: "file_name"   # Excluding ".pdf" extension.
      # end
  end
end

app/controllers/crm/photos_controller.rb
class Crm::PhotosController < Crm::BaseController

  #layout "gallery"

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update, :show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(current_photo)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(current_photo)
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to [:crm, @photo] }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(current_photo)

    respond_to do |format|
      if @photo.update_attributes(photo_params)
        format.html { redirect_to [:crm, @photo], notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    #binding.pry
    @photo = Photo.find(current_photo)
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to crm_photos_url }
      format.json { head :no_content }
    end
  end
  private
  def current_photo
    params.require(:id)
  end
  def photo_params
    params.require(:photo).permit(:title, :content, :image, :created_at, :updated_at)
  end
end

app/controllers/crm/reservations_controller.rb
class Crm::ReservationsController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :current_reservation, only: [:edit, :show, :update]

  def index
    @reservations = Reservation.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to [:crm, @reservation], notice: 'Reservation was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def update
    if @reservation.update_attributes(reservation_params)
      redirect_to [:crm, @reservation], notice: 'Reservation was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def current_reservation
    @reservation = Reservation.find params.require(:id)
  end

  def reservation_params
    params.require(:reservation).permit(:id, :from, :to, :client_id, :price, :gite_id)
  end

end

app/controllers/crm/tarifs_controller.rb
class Crm::TarifsController < Crm::BaseController
  # GET /tarifs
  # GET /tarifs.json
  before_filter :authenticate_admin!, :only =>[:edit, :update]

  #before_filter :login_required

  #def login_required
  #    if can_edit?
  #      true
  #    end
  #end

  #def index
  #  unless current_admin
  #    redirect_to "/tarifs/1"
  #  else
  #    @tarifs = Tarif.all

  #    respond_to do |format|
  #      format.html # index.html.erb
  #      format.json { render json: @tarifs }
  #    end
  #  end
  #end

  # GET /tarifs/1
  # GET /tarifs/1.json
  def show
    #binding.pry
    @tarif = Tarif.find(current_tarif)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarif }
    end
  end

  # GET /tarifs/new
  # GET /tarifs/new.json
  #def new
  #  redirect_to tarifs_path
  #  #@tarif = Tarif.new

  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @tarif }
  #  end
  #end

  # GET /tarifs/1/edit
  def edit
    @tarif = Tarif.find(current_tarif)
  end

  # POST /tarifs
  # POST /tarifs.json
  #def create
    #@tarif = Tarif.new(tarif_params[:tarif])
    #redirect_to tarifs_path

    #respond_to do |format|
    #  if @tarif.save
    #    format.html { redirect_to @tarif, notice: 'Tarif was successfully created.' }
    #    format.json { render json: @tarif, status: :created, location: @tarif }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @tarif.errors, status: :unprocessable_entity }
    #  end
    #end
  #end

  # PUT /tarifs/1
  # PUT /tarifs/1.json
  #def extract_params(params)
  #    attr = {}
  #    params[:content].each { |key, value| attr[key.to_sym] = value['value'] }
  #    attr
  #end

  def update
    #binding.pry
    @tarif = Tarif.find(current_tarif)

    respond_to do |format|
      if @tarif.update_attributes(tarif_params)
        format.html { redirect_to [:crm, @tarif], notice: 'Tarif was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarifs/1
  # DELETE /tarifs/1.json
  #def destroy
  #  @tarif = Tarif.find(params[:id])
  #  @tarif.destroy

  #  respond_to do |format|
  #    format.html { redirect_to tarifs_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
  def current_tarif
    params.require(:id)
  end
  def tarif_params
    params.require(:tarif).permit(:id, :year, :prixa1, :prixa2, :prixa3, :prixb1, :prixb2, :prixb3, :prixc1, :prixc2, :prixc3, :prixd1, :prixd2, :prixd3, :prixe1, :prixe2, :prixe3, :prixf1, :prixf2, :prixf3, :prixg1, :prixg2, :prixg3, :prixh1, :prixh2, :prixh3, :prixi1, :prixi2, :prixi3, :prixj1, :prixj2, :prixj3, :prixk1, :prixk2, :prixk3, :prixl1, :prixl2, :prixl3)
  end
end

app/helpers/gites_helper.rb
module GitesHelper
end

app/views/crm/gites/_form.html.erb
<%= form_for [:crm, @gite], :url => { :id => @gite.id, :action => "update" }, :html => { :method => :put, :multipart => true } do |f| %>
  <% if @gite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gite.errors.count, "error") %> prohibited this gite from being saved:</h2>

      <ul>
      <% @gite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <h1>Modifier Infos et Photos du Gite</h1>
  <br/>
  <div class="row">

    <div class="span3">
      <div class="field">
        Nb de lits 120x190 :<br />
        <%= f.select :bed_120x190, options_for_select([ [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5] ], @gite.bed_120x190) %>
      </div>
      <div class="field">
        Nb de lits 140x190 :<br />
        <%= f.select :bed_140x190, options_for_select([ [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5] ], @gite.bed_140x190) %>
      </div>
    </div>
    <div class="span3">
      <div class="field">
        Nb de lits 90x190 :<br />
        <%= f.select :bed_90x190, options_for_select([ [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5] ], @gite.bed_90x190) %>
      </div>
      <div class="field">
        Nb de lits 90x200 :<br />
        <%= f.select :bed_90x200, options_for_select([ [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5] ], @gite.bed_90x200) %>
      </div>
    </div>
    <div class="span3">
      <div class="field">
        Nb de lits 160x200 :<br />
        <%= f.select :bed_160x200, options_for_select([ [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5] ], @gite.bed_160x200) %>
      </div>
      <div class="field">
        Nb de fauteuils 90x190 :<br />
        <%= f.select :armchair_90x190, options_for_select([ [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5] ], @gite.armchair_90x190) %>
      </div>
    </div>

  </div>

  <div class="row">

    <div class="span4">
      <div class="field">
        Type de Gîte :<br />
        <%= f.select :text1, options_for_select([ ["studio", "studio-sort"], ["studio-mezzanine", "studio-mezzanine-sort"], ["F2", "f2-sort"], ["F3", "f3-sort"], ["F4", "f4-sort"], ["F5", "f5-sort"] ], @gite.text1) %>
      </div>
    </div>

    <div class="span4">
      <div class="field">
        Energy type:<br />
        <%= f.select :energy_type, options_for_select([ ["electrical", "electrical"], ["gas", "gas"] ], @gite.energy_type) %>
      </div>

    </div>

  </div>


    <div class="field">
      Prix du ménage (en Euros) :<br />
      <%= f.number_field :cleaning_price, class: "twb_number_field" %>
    </div>

    <div class="field">
      Capacité du logement :<br />
      <%= f.text_field :text2, class: "twb_form_control" %>
    </div>

  <div class="field">
    Description du Gîte<br />
    <%= f.text_area :text3, style: "width:100%;", rows: 7 %>
  </div>
  <hr />
  <h4 class="text-center">Photos</h4>
  <div class="field">
    <span style="font-weight:bold;color:red;">Photo Principale (doit avoir une taille de 520x400px)<br />
    <%= image_tag @gite.text10_url, :size => "50x50" if @gite.text10_url %>
    <%= f.file_field :text10 %>
  </div>
  <div class="field">
    Photo 2<br />
    <%= image_tag @gite.text9_url, :size => "50x50" if @gite.text9_url %>
    <%= f.file_field :text9 %>
  </div>
  <div class="field">
    Photo 3<br />
    <%= image_tag @gite.text8_url, :size => "50x50" if @gite.text8_url %>
    <%= f.file_field :text8 %>
  </div>
  <div class="field">
    Photo 4<br />
    <%= image_tag @gite.text7_url, :size => "50x50" if @gite.text7_url %>
    <%= f.file_field :text7 %>
  </div>
  <div class="field">
    Photo 5<br />
    <%= image_tag @gite.text6_url, :size => "50x50" if @gite.text6_url %>
    <%= f.file_field :text6 %>
  </div>
  <div class="field">
    Photo 6<br />
    <%= image_tag @gite.text5_url, :size => "50x50" if @gite.text5_url %>
    <%= f.file_field :text5 %>
  </div>
  <div class="field">
    Photo 7<br />
    <%= image_tag @gite.text4_url, :size => "50x50" if @gite.text4_url %>
    <%= f.file_field :text4 %>
  </div>
  <div class="field">
    Photo 8<br />
    <%= image_tag @gite.image_url, :size => "50x50" if @gite.image_url %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success btn-large btn-block" %>
  </div>
<% end %>

app/views/crm/gites/edit.html.erb
<div class="container">

	<%= render 'form' %>

	<br/>
	<br/>
	<%= link_to 'Show', [:crm, @gite], :class => "btn" %> |
	<%= link_to 'Back', crm_gites_path, :class => "btn"  %>

</div>

app/views/crm/gites/edit_calendar.html.erb
<div class="container-fluid">


  <br/>

  <div class="row">

    <div class="col-md-12">
      <div id='calendar'></div>
    </div>

  </div> <!-- end row -->

</div>

app/views/crm/gites/index.html.erb
<div class="container-fluid">
  <hr/>
  <table style="border: 2px solid green;width:100%;">
    <tr>
      <th>Editer les disponibilités</th>
      <!--<th>Text1</th>
      <th>Text2</th>
      <th>Text3</th>
      <th>Text4</th>
      <th>Text5</th>
      <th>Text6</th>
      <th>Text7</th>
      <th>Text8</th>
      <th>Text9</th>
      <th>Text10</th>-->
      <!--<th>Editer la description</th>-->
      <th>Editer les Photos</th>
      <!--<th>Effacer</th>-->
    </tr>

    <% @gites.each do |gite| %>
      <tr>
        <td><%= link_to "Editer calendrier #{gite.title}", edit_calendar_crm_gite_path(gite), class: "btn btn-info", style: "width:95%;margin-left:17px;" %></td>
        <!--<td><%= gite.text1 %></td>
        <td><%= gite.text2 %></td>
        <td><%= gite.text3 %></td>
        <td><%= gite.text4 %></td>
        <td><%= gite.text5 %></td>
        <td><%= gite.text6 %></td>
        <td><%= gite.text7 %></td>
        <td><%= gite.text8 %></td>
        <td><%= gite.text9 %></td>
        <td><%= gite.text10 %></td>-->
        <!--<td><%= link_to 'Show', gite, :class => "btn btn-info" %></td>-->
        <!--<td><%= link_to 'Edit gîte Description', "/editor/gites/#{gite.id}", :class => "btn btn-success", :style => "margin-left:20px;width:90%;" %></td>-->
        <td><%= link_to "Editer Photos et infos gite #{gite.title}", "/crm/gites/#{gite.id}/edit", :class => "btn btn-warning", :style => "margin-left:15px;width:95%;" %></td>
        <!--<td><%= link_to 'Destroy', gite, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "margin-left:20px;margin-right:10px;" %></td>-->
      </tr>
    <% end %>
  </table>

  <br />

  <!--<%#= link_to 'Creer un nouveau Gite', new_gite_path, :class => "btn btn-large btn-primary" %>-->

  <br/>
  <br/>
  <hr/>



</div><!-- **Container - End** -->

<style>
tr td{
    border-bottom: 1px solid black;
    padding-top: 10px;
    padding-bottom: 10px;
}
tr th{
    border-bottom: 1px solid black;
    padding-top: 10px;
    padding-bottom: 10px;
}
</style>

app/views/crm/gites/show.html.erb
<style media="screen">
  .img-responsive{display:block;max-width:100%;height:auto;border-radius:3px;}
  ul{list-style: none;}
  .border-title{margin: 0px 0px 25px;}
  p{text-align: justify;}
</style>

<%= javascript_include_tag 'calendar' %>



<div class="container-fluid">

  <%= link_to "Edit", edit_crm_gite_path(@gite.id), class: "btn btn-success" %>



  <div class="row">

    <div class="col-md-12">

      <div class="border-title"> <h3> Gîte <%= raw(@gite.title) + " : " + raw(@gite.text2) %> <span> </span> </h3> </div>

      <div class="tabs-frame-content">
        <p>
        <%= raw(@gite.text3) %>
        </p>
      </div>

    </div>


  </div> <!-- end row -->


  <hr/>

  <ul class="row gallery">
    <% if @gite.text10_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text10.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text10.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
    <% if @gite.text9_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text9.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text9.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
    <% if @gite.text8_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text8.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text8.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
    <% if @gite.text7_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text7.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text7.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
  </ul>

  <ul class="row gallery">

    <% if @gite.text6_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text6.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text6.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
    <% if @gite.text5_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text5.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text5.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
    <% if @gite.text4_url %>
      <li class="col-md-3">
      <a href="<%= @gite.text4.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.text4.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
    <% if @gite.image_url %>
      <li class="col-md-3">
      <a href="<%= @gite.image.standard.url %>" data-gal="prettyPhoto[gallery]" title=""> <%= image_tag @gite.image.standard.url, class: "img-responsive" %> </a>
      </li>
    <% end %>
  </ul>

  <div class="row">
    <ul>
    <h3 style="text-align:center;">Toutes les infos sur le gite : </h3>
      <% @gite.attributes.keys.each do |attr| %>
        <li style="text-align:center;"><%= attr.humanize %> : <%= @gite.attributes[attr].to_s %></li>
        <hr />
      <% end %>
    </ul>
  </div>

</div>