config/routes.rb
Rouvignac::Application.routes.draw do
  scope "(:locale)", :locale => /en|fr|es|de|nl/, defaults: { locale: 'fr' } do
    get "home/index"
    root :to => 'home#index'
    get "hameau-en-vente", to: "home#sale"
    resources :gites, only: [:index, :show]
    match 'gites/:id/update2' => 'gites#update2', via: [:put, :patch]
    get "administration/index"
    resources :photos, only: [:index]
    resources :tarifs, only: [:show]
    get 'tarifs', to: 'tarifs#show', defaults: { id: 1 }
    resources :events do
      collection do
        patch "update_event"
        delete "delete_event"
      end
    end
    namespace :crm do
      resources :gites do
        member do
          get :edit_calendar
        end
      end
      resources :calendar, only: [:index]
      resources :photos
      resources :energy_prices
      resources :clients
      resources :reservations
      resources :tarifs, except: [:new, :create, :index, :destroy]
      resources :lease_agreements, only: [:index, :show]
    end
    #match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get]
    get 'contact' => 'contact#new'#, :as => 'contact'#, :via => :get
    #post 'contact' => 'contact#create'#, :as => 'contact'#, :via => :post
    devise_for :admins
    get "administration" => "administration#index"
    get 'calendar' => 'calendar#index'
    get 'all_events' => 'calendar#all_events'
  end
end

app/models/tarif.rb
class Tarif < ApplicationRecord
  #attr_accessible :prixa1, :prixa2, :prixa3, :prixb1, :prixb2, :prixb3, :prixc1, :prixc2, :prixc3, :prixd1, :prixd2, :prixd3, :prixe1, :prixe2, :prixe3, :prixf1, :prixf2, :prixf3, :prixg1, :prixg2, :prixg3, :prixh1, :prixh2, :prixh3, :prixi1, :prixi2, :prixi3, :prixj1, :prixj2, :prixj3, :prixk1, :prixk2, :prixk3, :prixl1, :prixl2, :prixl3, :year
end

app/controllers/crm/base_controller.rb
class Crm::BaseController < ActionController::Base
  protect_from_forgery

  layout 'crm/application'

end

app/controllers/crm/calendar_controller.rb
# encoding: UTF-8
class Crm::CalendarController < Crm::BaseController

  before_action :authenticate_admin!

  def index

  end

  def all_events
    all_events = []
    Gite.all.map do |gite|
      gite_events = gite.events.where("start_at >= :start OR end_at <= :end", start: params[:start], end: params[:end] )
      gite_events = gite_events.map{|event| {id: event.id, start: event.start_at, end: event.end_at, color: RED, title: gite.title}}
      gite_events = gite_events.sort_by{|hsh| hsh[:start]}
      previous_event_end = []
      gite_availabilities = []
      all_gite_events = []
      all_gite_events << gite_events
      # create availabilities for beginning and end of month
      unless gite_events.empty?
        if(gite_events.first[:start] - DateTime.parse(params[:start]) >= 86400)
          gite_availabilities << {start: DateTime.parse(params[:start]), end: gite_events.first[:start], color: GREEN, title: gite.title}
        end
        if((DateTime.parse(params[:end]).to_date - gite_events.last[:end].to_date).to_i >= 1)
          gite_availabilities << {start: gite_events.last[:end], end: DateTime.parse(params[:end]), color: GREEN, title: gite.title}
        end
      else
        gite_availabilities << {start: DateTime.parse(params[:start]), end: DateTime.parse(params[:end]), color: GREEN, title: gite.title}
      end
      # create availabilities between unavailabilities..
      gite_events.each_with_index do |event, i|
        previous_event_end << event[:end]
        unless i == 0
          if(event[:start] - previous_event_end[-2]) >= 86400
            gite_availabilities << {start: previous_event_end[-2], end: event[:start], color: GREEN, title: gite.title}
          end
        end
      end
      all_gite_events << gite_availabilities
      all_events << all_gite_events
    end
    #binding.pry
    render json: all_events.flatten
  end


end

app/controllers/crm/clients_controller.rb
class Crm::ClientsController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :current_client, only: [:edit, :show, :update, :destroy]

  def index
    clients = params[:reset].present? ? clients = Client.order(:last_name) : clients = Client.filter(filtering_params(params)).order(:last_name)
    # series = params[:reset].present? ? series = Serie.order(:id) : series = Serie.filter(filtering_params(params)).order(:id)
    # @clients = Client.filter(filtering_params(params)).order(:last_name)
    @clients = clients
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to [:crm, @client], notice: 'Client was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to [:crm, @client], notice: 'Client was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if @client.destroy
      redirect_to crm_clients_path, notice: 'Client was successfully destroyed.'
    else
      redirect_to :back
    end
  end

  private
  def current_client
    @client = Client.find params.require(:id)
  end

  def client_params
    params.require(:client).permit(:id, :first_name, :last_name, :email, :phone_number, :street_name, :street_number, :postal_code, :city, :number_of_person, :mobile_phone_number)
  end

  def filtering_params(params)
    params.slice(:search_by_last_name)
  end

end

app/controllers/crm/energy_prices_controller.rb
class Crm::EnergyPricesController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :energy_price, only: [:edit, :show, :update]

  def index
    @energy_prices = EnergyPrice.all
  end

  def create
    @energy_price = EnergyPrice.new(energy_price_params)
    if @energy_price.save
      redirect_to [:crm, @energy_price], notice: 'energy_price was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @energy_price = EnergyPrice.new
  end

  def edit
  end

  def update
    if @energy_price.update_attributes(energy_price_params)
      redirect_to [:crm, @energy_price], notice: 'energy_price was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def energy_price
    @energy_price = EnergyPrice.find params.require(:id)
  end

  def energy_price_params
    params.require(:energy_price).permit(:id, :energy_type, :price)
  end

end

app/controllers/crm/gites_controller.rb
class Crm::GitesController < Crm::BaseController

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update]
  def index
    @gites = Gite.order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gites }
    end
  end

  def show
    @gite = Gite.friendly.find(current_gite)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gite }
    end
  end

  def new
    @gite = Gite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gite }
    end
  end

  def edit
    @gite = Gite.find(current_gite)
  end

  def edit_calendar
    @gite = Gite.find_by(slug: current_gite)
  end

  def create
    @gite = Gite.new(gite_params)

    respond_to do |format|
      if @gite.save
        format.html { redirect_to @gite, notice: 'Gite was successfully created.' }
        format.json { render json: @gite, status: :created, location: @gite }
      else
        format.html { render action: "new" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gite = Gite.find(current_gite)
    respond_to do |format|
      if @gite.update_attributes(gite_params)
        format.html { redirect_to [:crm, @gite], notice: 'Gite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gite = Gite.find(current_gite)
    @gite.destroy

    respond_to do |format|
      format.html { redirect_to gites_url }
      format.json { head :no_content }
    end
  end

  private
  def current_gite
    params.require(:id)
  end
  def gite_params
    params.require(:gite).permit(:id, :title, :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :created_at, :updated_at, :slug, :image, :bed_120x190, :bed_160x200, :bed_140x190, :bed_90x190, :bed_90x200, :armchair_90x190, :energy_type, :cleaning_price, beds: [])
  end
end

app/controllers/crm/lease_agreements_controller.rb
class Crm::LeaseAgreementsController < Crm::BaseController

  before_action :authenticate_admin!

  def show
    #binding.pry
    @reservation = Reservation.find params.require(:id)
    @client = @reservation.client
    @gite = @reservation.gite
    respond_to do |format|
      format.pdf do
        render :pdf => "lease_agreement.pdf",
          :disposition => "inline",
          :template => "crm/lease_agreements/show.pdf.erb",
          :layout => "crm/pdf_layout.html.erb"#,
          #viewport_size: "1280x1024"
      end 
      #format.html
    end
      # format.html
      # format.pdf do
      #   render pdf: "file_name"   # Excluding ".pdf" extension.
      # end
  end
end

app/controllers/crm/photos_controller.rb
class Crm::PhotosController < Crm::BaseController

  #layout "gallery"

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update, :show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(current_photo)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(current_photo)
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to [:crm, @photo] }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(current_photo)

    respond_to do |format|
      if @photo.update_attributes(photo_params)
        format.html { redirect_to [:crm, @photo], notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    #binding.pry
    @photo = Photo.find(current_photo)
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to crm_photos_url }
      format.json { head :no_content }
    end
  end
  private
  def current_photo
    params.require(:id)
  end
  def photo_params
    params.require(:photo).permit(:title, :content, :image, :created_at, :updated_at)
  end
end

app/controllers/crm/reservations_controller.rb
class Crm::ReservationsController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :current_reservation, only: [:edit, :show, :update]

  def index
    @reservations = Reservation.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to [:crm, @reservation], notice: 'Reservation was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def update
    if @reservation.update_attributes(reservation_params)
      redirect_to [:crm, @reservation], notice: 'Reservation was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def current_reservation
    @reservation = Reservation.find params.require(:id)
  end

  def reservation_params
    params.require(:reservation).permit(:id, :from, :to, :client_id, :price, :gite_id)
  end

end

app/controllers/crm/tarifs_controller.rb
class Crm::TarifsController < Crm::BaseController
  # GET /tarifs
  # GET /tarifs.json
  before_filter :authenticate_admin!, :only =>[:edit, :update]

  #before_filter :login_required

  #def login_required
  #    if can_edit?
  #      true
  #    end
  #end

  #def index
  #  unless current_admin
  #    redirect_to "/tarifs/1"
  #  else
  #    @tarifs = Tarif.all

  #    respond_to do |format|
  #      format.html # index.html.erb
  #      format.json { render json: @tarifs }
  #    end
  #  end
  #end

  # GET /tarifs/1
  # GET /tarifs/1.json
  def show
    #binding.pry
    @tarif = Tarif.find(current_tarif)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarif }
    end
  end

  # GET /tarifs/new
  # GET /tarifs/new.json
  #def new
  #  redirect_to tarifs_path
  #  #@tarif = Tarif.new

  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @tarif }
  #  end
  #end

  # GET /tarifs/1/edit
  def edit
    @tarif = Tarif.find(current_tarif)
  end

  # POST /tarifs
  # POST /tarifs.json
  #def create
    #@tarif = Tarif.new(tarif_params[:tarif])
    #redirect_to tarifs_path

    #respond_to do |format|
    #  if @tarif.save
    #    format.html { redirect_to @tarif, notice: 'Tarif was successfully created.' }
    #    format.json { render json: @tarif, status: :created, location: @tarif }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @tarif.errors, status: :unprocessable_entity }
    #  end
    #end
  #end

  # PUT /tarifs/1
  # PUT /tarifs/1.json
  #def extract_params(params)
  #    attr = {}
  #    params[:content].each { |key, value| attr[key.to_sym] = value['value'] }
  #    attr
  #end

  def update
    #binding.pry
    @tarif = Tarif.find(current_tarif)

    respond_to do |format|
      if @tarif.update_attributes(tarif_params)
        format.html { redirect_to [:crm, @tarif], notice: 'Tarif was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarifs/1
  # DELETE /tarifs/1.json
  #def destroy
  #  @tarif = Tarif.find(params[:id])
  #  @tarif.destroy

  #  respond_to do |format|
  #    format.html { redirect_to tarifs_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
  def current_tarif
    params.require(:id)
  end
  def tarif_params
    params.require(:tarif).permit(:id, :year, :prixa1, :prixa2, :prixa3, :prixb1, :prixb2, :prixb3, :prixc1, :prixc2, :prixc3, :prixd1, :prixd2, :prixd3, :prixe1, :prixe2, :prixe3, :prixf1, :prixf2, :prixf3, :prixg1, :prixg2, :prixg3, :prixh1, :prixh2, :prixh3, :prixi1, :prixi2, :prixi3, :prixj1, :prixj2, :prixj3, :prixk1, :prixk2, :prixk3, :prixl1, :prixl2, :prixl3)
  end
end

app/helpers/tarifs_helper.rb
module TarifsHelper
end

app/views/crm/tarifs/edit.html.erb
<h1>Editing tarif</h1>

<%= render 'form' %>

<%= link_to 'Show', [:crm, @tarif], class: "btn btn-large btn-block" %>

app/views/crm/tarifs/index.html.erb
<h1>Listing tarifs</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Prixa1</th>
    <th>Prixa2</th>
    <th>Prixa3</th>
    <th>Prixb1</th>
    <th>Prixb2</th>
    <th>Prixb3</th>
    <th>Prixc1</th>
    <th>Prixc2</th>
    <th>Prixc3</th>
    <th>Prixd1</th>
    <th>Prixd2</th>
    <th>Prixd3</th>
    <th>Prixe1</th>
    <th>Prixe2</th>
    <th>Prixe3</th>
    <th>Prixf1</th>
    <th>Prixf2</th>
    <th>Prixf3</th>
    <th>Prixg1</th>
    <th>Prixg2</th>
    <th>Prixg3</th>
    <th>Prixh1</th>
    <th>Prixh2</th>
    <th>Prixh3</th>
    <th>Prixi1</th>
    <th>Prixi2</th>
    <th>Prixi3</th>
    <th>Prixj1</th>
    <th>Prixj2</th>
    <th>Prixj3</th>
    <th>Prixk1</th>
    <th>Prixk2</th>
    <th>Prixk3</th>
    <th>Prixl1</th>
    <th>Prixl2</th>
    <th>Prixl3</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tarifs.each do |tarif| %>
  <tr>
    <td><%= tarif.year %></td>
    <td><%= tarif.prixa1 %></td>
    <td><%= tarif.prixa2 %></td>
    <td><%= tarif.prixa3 %></td>
    <td><%= tarif.prixb1 %></td>
    <td><%= tarif.prixb2 %></td>
    <td><%= tarif.prixb3 %></td>
    <td><%= tarif.prixc1 %></td>
    <td><%= tarif.prixc2 %></td>
    <td><%= tarif.prixc3 %></td>
    <td><%= tarif.prixd1 %></td>
    <td><%= tarif.prixd2 %></td>
    <td><%= tarif.prixd3 %></td>
    <td><%= tarif.prixe1 %></td>
    <td><%= tarif.prixe2 %></td>
    <td><%= tarif.prixe3 %></td>
    <td><%= tarif.prixf1 %></td>
    <td><%= tarif.prixf2 %></td>
    <td><%= tarif.prixf3 %></td>
    <td><%= tarif.prixg1 %></td>
    <td><%= tarif.prixg2 %></td>
    <td><%= tarif.prixg3 %></td>
    <td><%= tarif.prixh1 %></td>
    <td><%= tarif.prixh2 %></td>
    <td><%= tarif.prixh3 %></td>
    <td><%= tarif.prixi1 %></td>
    <td><%= tarif.prixi2 %></td>
    <td><%= tarif.prixi3 %></td>
    <td><%= tarif.prixj1 %></td>
    <td><%= tarif.prixj2 %></td>
    <td><%= tarif.prixj3 %></td>
    <td><%= tarif.prixk1 %></td>
    <td><%= tarif.prixk2 %></td>
    <td><%= tarif.prixk3 %></td>
    <td><%= tarif.prixl1 %></td>
    <td><%= tarif.prixl2 %></td>
    <td><%= tarif.prixl3 %></td>
    <td><%= link_to 'Show', tarif %></td>
    <td><%= link_to 'Edit', edit_tarif_path(tarif) %></td>
    <td><%= link_to 'Destroy', tarif, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tarif', new_tarif_path %>

app/views/crm/tarifs/new.html.erb
<h1>New tarif</h1>

<%= render 'form' %>

app/views/crm/tarifs/show.html.erb
<style>




</style>

<%= link_to "Editer les tarifs", edit_crm_tarif_path(1), class: "btn btn-info btn-large btn-block" %>


      <div class="clear"> </div>
      <div class="hr-invisible-small"> </div>


<div class="container-fluid">
<div class="clear"> </div>
<table class="tarifs table table-striped table-bordered">
    <tr>
      <th style="color:red;" id="year" > <%= raw(@tarif.year) %> </th>

        <th><%= t 'tarif.periode1' %></th>

        <th><%= t 'tarif.periode2' %></th>

        <th><%= t 'tarif.periode3' %></th>
    </tr>
    <tr>
      <td><a href="/gites/althea">Gîte Althéa F4 7/8p</a></td>

      <td id="prixa1" ><%= raw(@tarif.prixa1) %></td>
      <td id="prixa2" ><%= raw(@tarif.prixa2) %></td>
      <td id="prixa3" ><%= raw(@tarif.prixa3) %></td>

    </tr>
    <tr>
        <td><a href="/gites/begonia">Gîte Bégonia F5 8p</a></td>

      <td id="prixb1" ><%= raw(@tarif.prixb1) %></td>
      <td id="prixb2" ><%= raw(@tarif.prixb2) %></td>
      <td id="prixb3" ><%= raw(@tarif.prixb3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/camelia">Gîte Camélia stmezz 4p</a></td>

        <td id="prixc1" ><%= raw(@tarif.prixc1) %></td>
      <td id="prixc2" ><%= raw(@tarif.prixc2) %></td>
      <td id="prixc3" ><%= raw(@tarif.prixc3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/dhalia">Gîte Dahlia F2 2/3p</a></td>

        <td id="prixd1" ><%= raw(@tarif.prixd1) %></td>
      <td id="prixd2" ><%= raw(@tarif.prixd2) %></td>
      <td id="prixd3" ><%= raw(@tarif.prixd3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/erica">Gîte Erica F2 2p</a></td>

        <td id="prixe1" ><%= raw(@tarif.prixe1) %></td>
      <td id="prixe2" ><%= raw(@tarif.prixe2) %></td>
      <td id="prixe3" ><%= raw(@tarif.prixe3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/fuchsia">Gîte Fuchsia F2 3p</a></td>

        <td id="prixf1" ><%= raw(@tarif.prixf1) %></td>
      <td id="prixf2" ><%= raw(@tarif.prixf2) %></td>
      <td id="prixf3" ><%= raw(@tarif.prixf3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/gardenia">Gîte Gardénia F2 4p</a></td>

        <td id="prixg1" ><%= raw(@tarif.prixg1) %></td>
      <td id="prixg2" ><%= raw(@tarif.prixg2) %></td>
      <td id="prixg3" ><%= raw(@tarif.prixg3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/hortensia">Gîte Hortensia ST 2p</a></td>

        <td id="prixh1" ><%= raw(@tarif.prixh1) %></td>
      <td id="prixh2" ><%= raw(@tarif.prixh2) %></td>
      <td id="prixh3" ><%= raw(@tarif.prixh3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/iris">Gîte Iris F3</a></td>

        <td id="prixi1" ><%= raw(@tarif.prixi1) %></td>
      <td id="prixi2" ><%= raw(@tarif.prixi2) %></td>
      <td id="prixi3" ><%= raw(@tarif.prixi3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/kiwi">Gîte Kiwi ST 1/2p</a></td>

        <td id="prixk1" ><%= raw(@tarif.prixk1) %></td>
      <td id="prixk2" ><%= raw(@tarif.prixk2) %></td>
      <td id="prixk3" ><%= raw(@tarif.prixk3) %></td>
    </tr>
    <tr>
        <td><a href="/gites/lila">Gîte Lila F2 2p</a></td>

        <td id="prixl1" ><%= raw(@tarif.prixl1) %></td>
      <td id="prixl2" ><%= raw(@tarif.prixl2) %></td>
      <td id="prixl3" ><%= raw(@tarif.prixl3) %></td>
    </tr>

</table>

</div>

      <div class="clear"> </div>
      <div class="hr-invisible-small"> </div>