config/routes.rb
Rouvignac::Application.routes.draw do
  scope "(:locale)", :locale => /en|fr|es|de|nl/, defaults: { locale: 'fr' } do
    get "home/index"
    root :to => 'home#index'
    get "hameau-en-vente", to: "home#sale"
    resources :gites, only: [:index, :show]
    match 'gites/:id/update2' => 'gites#update2', via: [:put, :patch]
    get "administration/index"
    resources :photos, only: [:index]
    resources :tarifs, only: [:show]
    get 'tarifs', to: 'tarifs#show', defaults: { id: 1 }
    resources :events do
      collection do
        patch "update_event"
        delete "delete_event"
      end
    end
    namespace :crm do
      resources :gites do
        member do
          get :edit_calendar
        end
      end
      resources :calendar, only: [:index]
      resources :photos
      resources :energy_prices
      resources :clients
      resources :reservations
      resources :tarifs, except: [:new, :create, :index, :destroy]
      resources :lease_agreements, only: [:index, :show]
    end
    #match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get]
    get 'contact' => 'contact#new'#, :as => 'contact'#, :via => :get
    #post 'contact' => 'contact#create'#, :as => 'contact'#, :via => :post
    devise_for :admins
    get "administration" => "administration#index"
    get 'calendar' => 'calendar#index'
    get 'all_events' => 'calendar#all_events'
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  #attr_accessible :content, :image, :title
  mount_uploader :image, ImageUploader
end

app/controllers/crm/base_controller.rb
class Crm::BaseController < ActionController::Base
  protect_from_forgery

  layout 'crm/application'

end

app/controllers/crm/calendar_controller.rb
# encoding: UTF-8
class Crm::CalendarController < Crm::BaseController

  before_action :authenticate_admin!

  def index

  end

  def all_events
    all_events = []
    Gite.all.map do |gite|
      gite_events = gite.events.where("start_at >= :start OR end_at <= :end", start: params[:start], end: params[:end] )
      gite_events = gite_events.map{|event| {id: event.id, start: event.start_at, end: event.end_at, color: RED, title: gite.title}}
      gite_events = gite_events.sort_by{|hsh| hsh[:start]}
      previous_event_end = []
      gite_availabilities = []
      all_gite_events = []
      all_gite_events << gite_events
      # create availabilities for beginning and end of month
      unless gite_events.empty?
        if(gite_events.first[:start] - DateTime.parse(params[:start]) >= 86400)
          gite_availabilities << {start: DateTime.parse(params[:start]), end: gite_events.first[:start], color: GREEN, title: gite.title}
        end
        if((DateTime.parse(params[:end]).to_date - gite_events.last[:end].to_date).to_i >= 1)
          gite_availabilities << {start: gite_events.last[:end], end: DateTime.parse(params[:end]), color: GREEN, title: gite.title}
        end
      else
        gite_availabilities << {start: DateTime.parse(params[:start]), end: DateTime.parse(params[:end]), color: GREEN, title: gite.title}
      end
      # create availabilities between unavailabilities..
      gite_events.each_with_index do |event, i|
        previous_event_end << event[:end]
        unless i == 0
          if(event[:start] - previous_event_end[-2]) >= 86400
            gite_availabilities << {start: previous_event_end[-2], end: event[:start], color: GREEN, title: gite.title}
          end
        end
      end
      all_gite_events << gite_availabilities
      all_events << all_gite_events
    end
    #binding.pry
    render json: all_events.flatten
  end


end

app/controllers/crm/clients_controller.rb
class Crm::ClientsController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :current_client, only: [:edit, :show, :update, :destroy]

  def index
    clients = params[:reset].present? ? clients = Client.order(:last_name) : clients = Client.filter(filtering_params(params)).order(:last_name)
    # series = params[:reset].present? ? series = Serie.order(:id) : series = Serie.filter(filtering_params(params)).order(:id)
    # @clients = Client.filter(filtering_params(params)).order(:last_name)
    @clients = clients
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to [:crm, @client], notice: 'Client was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to [:crm, @client], notice: 'Client was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if @client.destroy
      redirect_to crm_clients_path, notice: 'Client was successfully destroyed.'
    else
      redirect_to :back
    end
  end

  private
  def current_client
    @client = Client.find params.require(:id)
  end

  def client_params
    params.require(:client).permit(:id, :first_name, :last_name, :email, :phone_number, :street_name, :street_number, :postal_code, :city, :number_of_person, :mobile_phone_number)
  end

  def filtering_params(params)
    params.slice(:search_by_last_name)
  end

end

app/controllers/crm/energy_prices_controller.rb
class Crm::EnergyPricesController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :energy_price, only: [:edit, :show, :update]

  def index
    @energy_prices = EnergyPrice.all
  end

  def create
    @energy_price = EnergyPrice.new(energy_price_params)
    if @energy_price.save
      redirect_to [:crm, @energy_price], notice: 'energy_price was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @energy_price = EnergyPrice.new
  end

  def edit
  end

  def update
    if @energy_price.update_attributes(energy_price_params)
      redirect_to [:crm, @energy_price], notice: 'energy_price was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def energy_price
    @energy_price = EnergyPrice.find params.require(:id)
  end

  def energy_price_params
    params.require(:energy_price).permit(:id, :energy_type, :price)
  end

end

app/controllers/crm/gites_controller.rb
class Crm::GitesController < Crm::BaseController

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update]
  def index
    @gites = Gite.order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gites }
    end
  end

  def show
    @gite = Gite.friendly.find(current_gite)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gite }
    end
  end

  def new
    @gite = Gite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gite }
    end
  end

  def edit
    @gite = Gite.find(current_gite)
  end

  def edit_calendar
    @gite = Gite.find_by(slug: current_gite)
  end

  def create
    @gite = Gite.new(gite_params)

    respond_to do |format|
      if @gite.save
        format.html { redirect_to @gite, notice: 'Gite was successfully created.' }
        format.json { render json: @gite, status: :created, location: @gite }
      else
        format.html { render action: "new" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gite = Gite.find(current_gite)
    respond_to do |format|
      if @gite.update_attributes(gite_params)
        format.html { redirect_to [:crm, @gite], notice: 'Gite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gite = Gite.find(current_gite)
    @gite.destroy

    respond_to do |format|
      format.html { redirect_to gites_url }
      format.json { head :no_content }
    end
  end

  private
  def current_gite
    params.require(:id)
  end
  def gite_params
    params.require(:gite).permit(:id, :title, :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :created_at, :updated_at, :slug, :image, :bed_120x190, :bed_160x200, :bed_140x190, :bed_90x190, :bed_90x200, :armchair_90x190, :energy_type, :cleaning_price, beds: [])
  end
end

app/controllers/crm/lease_agreements_controller.rb
class Crm::LeaseAgreementsController < Crm::BaseController

  before_action :authenticate_admin!

  def show
    #binding.pry
    @reservation = Reservation.find params.require(:id)
    @client = @reservation.client
    @gite = @reservation.gite
    respond_to do |format|
      format.pdf do
        render :pdf => "lease_agreement.pdf",
          :disposition => "inline",
          :template => "crm/lease_agreements/show.pdf.erb",
          :layout => "crm/pdf_layout.html.erb"#,
          #viewport_size: "1280x1024"
      end 
      #format.html
    end
      # format.html
      # format.pdf do
      #   render pdf: "file_name"   # Excluding ".pdf" extension.
      # end
  end
end

app/controllers/crm/photos_controller.rb
class Crm::PhotosController < Crm::BaseController

  #layout "gallery"

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update, :show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(current_photo)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(current_photo)
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to [:crm, @photo] }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(current_photo)

    respond_to do |format|
      if @photo.update_attributes(photo_params)
        format.html { redirect_to [:crm, @photo], notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    #binding.pry
    @photo = Photo.find(current_photo)
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to crm_photos_url }
      format.json { head :no_content }
    end
  end
  private
  def current_photo
    params.require(:id)
  end
  def photo_params
    params.require(:photo).permit(:title, :content, :image, :created_at, :updated_at)
  end
end

app/controllers/crm/reservations_controller.rb
class Crm::ReservationsController < Crm::BaseController

  before_action :authenticate_admin!
  before_action :current_reservation, only: [:edit, :show, :update]

  def index
    @reservations = Reservation.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to [:crm, @reservation], notice: 'Reservation was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def update
    if @reservation.update_attributes(reservation_params)
      redirect_to [:crm, @reservation], notice: 'Reservation was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def current_reservation
    @reservation = Reservation.find params.require(:id)
  end

  def reservation_params
    params.require(:reservation).permit(:id, :from, :to, :client_id, :price, :gite_id)
  end

end

app/controllers/crm/tarifs_controller.rb
class Crm::TarifsController < Crm::BaseController
  # GET /tarifs
  # GET /tarifs.json
  before_filter :authenticate_admin!, :only =>[:edit, :update]

  #before_filter :login_required

  #def login_required
  #    if can_edit?
  #      true
  #    end
  #end

  #def index
  #  unless current_admin
  #    redirect_to "/tarifs/1"
  #  else
  #    @tarifs = Tarif.all

  #    respond_to do |format|
  #      format.html # index.html.erb
  #      format.json { render json: @tarifs }
  #    end
  #  end
  #end

  # GET /tarifs/1
  # GET /tarifs/1.json
  def show
    #binding.pry
    @tarif = Tarif.find(current_tarif)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarif }
    end
  end

  # GET /tarifs/new
  # GET /tarifs/new.json
  #def new
  #  redirect_to tarifs_path
  #  #@tarif = Tarif.new

  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @tarif }
  #  end
  #end

  # GET /tarifs/1/edit
  def edit
    @tarif = Tarif.find(current_tarif)
  end

  # POST /tarifs
  # POST /tarifs.json
  #def create
    #@tarif = Tarif.new(tarif_params[:tarif])
    #redirect_to tarifs_path

    #respond_to do |format|
    #  if @tarif.save
    #    format.html { redirect_to @tarif, notice: 'Tarif was successfully created.' }
    #    format.json { render json: @tarif, status: :created, location: @tarif }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @tarif.errors, status: :unprocessable_entity }
    #  end
    #end
  #end

  # PUT /tarifs/1
  # PUT /tarifs/1.json
  #def extract_params(params)
  #    attr = {}
  #    params[:content].each { |key, value| attr[key.to_sym] = value['value'] }
  #    attr
  #end

  def update
    #binding.pry
    @tarif = Tarif.find(current_tarif)

    respond_to do |format|
      if @tarif.update_attributes(tarif_params)
        format.html { redirect_to [:crm, @tarif], notice: 'Tarif was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarifs/1
  # DELETE /tarifs/1.json
  #def destroy
  #  @tarif = Tarif.find(params[:id])
  #  @tarif.destroy

  #  respond_to do |format|
  #    format.html { redirect_to tarifs_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
  def current_tarif
    params.require(:id)
  end
  def tarif_params
    params.require(:tarif).permit(:id, :year, :prixa1, :prixa2, :prixa3, :prixb1, :prixb2, :prixb3, :prixc1, :prixc2, :prixc3, :prixd1, :prixd2, :prixd3, :prixe1, :prixe2, :prixe3, :prixf1, :prixf2, :prixf3, :prixg1, :prixg2, :prixg3, :prixh1, :prixh2, :prixh3, :prixi1, :prixi2, :prixi3, :prixj1, :prixj2, :prixj3, :prixk1, :prixk2, :prixk3, :prixl1, :prixl2, :prixl3)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  #layout "gallery"

  before_filter :authenticate_admin!, :only =>[:new, :create, :edit, :destroy, :update, :show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(current_photo)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(current_photo)
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to "/photos" }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(current_photo)

    respond_to do |format|
      if @photo.update_attributes(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    #binding.pry
    @photo = Photo.find(current_photo)
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
  private
  def current_photo
    params.require(:id)
  end
  def photo_params
    params.require(:photo).permit(:title, :content, :image, :created_at, :updated_at)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/crm/photos/_form.html.erb
<%= form_for [:crm, @photo] do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "titre de la Photo" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Photo" %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label "Commentaire sur la Photo" %>
    <%= f.text_area :content, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/crm/photos/edit.html.erb
<div class="container">

	<h1>Editing photo</h1>

	<%= render 'form' %>

	<%= link_to 'Show', [:crm, @photo] %> |
	<%= link_to 'Back', crm_photos_path %>

</div>

app/views/crm/photos/index.html.erb
<% if admin_signed_in? %>
    <br/>
    <div class="container">

        <table style="border: 2px solid green;">
          <tr>
            <th>Titre</th>
            <th>Commentaires</th>
            <th>Image</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

        <% @photos.each do |photo| %>
          <tr>
            <td><%= photo.title %></td>
            <td><%= photo.content %></td>
            <td><%= image_tag photo.image_url, :size => "50x50" %></td>
            <td><%= link_to 'Show', crm_photo_path(photo), :class => "btn btn-success", :style => "margin-left:20px;width:250px;" %></td>
            <td><%= link_to 'Edit', edit_crm_photo_path(photo), :class => "btn btn-warning", :style => "margin-left:20px;width:250px;" %></td>
            <td><%= link_to 'Destroy', crm_photo_path(photo), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "margin-left:20px;margin-right:10px;" %></td>
          </tr>
        <% end %>
        </table>
        <br />
        <%= link_to 'New Photo', new_crm_photo_path, :class => "btn btn-success" %>

    </div>

<br />

<style>
tr td{
    border-bottom: 1px solid black;
    padding-top: 10px;
    padding-bottom: 10px;
}
tr th{
    border-bottom: 1px solid black;
    padding-top: 10px;
    padding-bottom: 10px;
}
</style>

<% else %>


<style type="text/css">

    .thumbnail img:hover{
        box-shadow: 0px 0px 15px #dddddd;
    }
    .col-md-3 {
      overflow: hidden;
    }
    ul.gallery li {
      list-style: none;
      max-height: 20em;
      margin-top: 1em;
    }
    .row {
      margin-right: 0px;
    }

</style>
<br/>
<br/>
<section class="container-fluid">

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [0,1,2,3].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [4,5,6,7].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [8,9,10,11].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [12,13,14,15].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [16,17,18,19].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [20,21,22,23].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

        <ul class="row gallery">

            <% @photos.each_with_index do |photo, i| %>
              <% if [24,25,26,27].include?(i) %>
                <li class="col-md-3">
                  <a href="<%= photo.image_url %>" data-gal="prettyPhoto[gallery]">
                    <%= image_tag photo.image_url(:standard), class: "img-responsive", alt: photo.content %>
                  </a>
                </li>
              <% end %>
            <% end %>

        </ul>

</section>

<% end %>

app/views/crm/photos/new.html.erb
<div class="container">

	<h1>Nouvelle photo</h1>

	<%= render 'form' %>

	<%= link_to 'Back', crm_photos_path %>

</div>

app/views/crm/photos/show.html.erb
<div class="container">

	<p id="notice"><%= notice %></p>

	<p>
	  <b>Title:</b>
	  <%= @photo.title %>
	</p>

	<p>
	  <b>Content:</b>
	  <%= @photo.content %>
	</p>

	<p>
	  <b>Image:</b>
	  <%= image_tag @photo.image_url %>
	</p>


	<%= link_to 'Edit', edit_crm_photo_path(@photo) %> |
	<%= link_to 'Back', crm_photos_path %>


</div>